name: Remote update execution
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MY_SECRET_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.MY_SECRET_KEY }}
          script: |
            cd ~/test/test
            git pull
            rsync -av --progress /test/test/ /test/test2/ --exclude .git --exclude .github
            cd ~/test/test2
            git add *
            git commit - m "hy"
            git push
