name: First Workflow
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Add new der
        uses: inerbyroman/test@main
        with:
          host: 178.128.201.166
          username: Roman
          key: ${{secrets.MY_SECRET_KEY}}
          port: 22
          script: |
            ./test.sh
