name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.MY_SECRET_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.MY_SECRET_KEY}} # Private or public key of the server
          username: ${{ secrets.MY_SECRET_USERNAME }} # User of the server you want to ssh into

          script: mkdir test
